try:
    raise Exception("This is a except")
except Exception as e:
    print(e)